2.

SELECT DISTINCT ?class
WHERE {
?class a rdfs:Class
}


3.

SELECT ?class ?subClass 
WHERE {
?subClass rdfs:subClassOf ?class
?class a rdfs:Class
}
ORDER BY ?class


4.

SELECT ?definitions 
WHERE
{
  ?property rdfs:label "shoe size"@en
  ?property rdfs:comment ?definitions 
}


5.

SELECT ?synonyms
WHERE
{
  ?person rdfs:label "person"@en
  ?person rdfs:label ?synonyms
  FILTER ( ?synonyms != "personne"@fr && lang(?synonyms) = 'fr' )
}